<xsl:transform version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sap="http://www.sap.com/sapxsl"
>
<!--
*
* Copyright (c) 2011-2013 Servicecenter for Medical Informatics,
* Wuerzburg University Hospital, Germany. All rights reserved.
* Use is subject to license terms.
* http://goo.gl/dTqqQM
*
-->

<xsl:template match="/">
<html>
  <head>
  </head>
  <body>
    <div>Hello, <b>World</b>!</div>
  </body>
</html>
</xsl:template>

</xsl:transform>
